### ISSUE TITLE
Буква залезает на края в шифре организации с буквой "Д"

### ISSUE THREAD

**Issue by utalua** [Metrolog/marks#32]
При создании макета для Карельского ЦСМ с шифром "АД" нижняя часть буквы "Д" залезла на контур круга. 
[Karelia.pdf](https://github.com/Metrolog/marks/files/1394362/Karelia.pdf)

**Comment by sergey-s-betke** [comment]
[test2.pdf](https://github.com/Metrolog/marks/files/1424234/test2.pdf)

**Comment by sergey-s-betke** [comment]
Конкретно эта ошибка исправлена. И для любых двухбуквенных шифров проблем больше быть не должно. Однако, для трёхбуквенных шифров (не для ЦСМ и институтов Росстандарта) всё ещё возможны проблемы с шириной шифра. В этом случае попробую вычислять ширину шифра и масштабировать шрифт шифра по горизонтали, вписывая его в необходимый размер.

Возможно, вообще стоит подготовить макросы для вписывания элементов в области заданных размеров. Если вписывается - выводим без масштабирования, не вписывается - масштабируем.

**Comment by utalua** [comment]
[смещена первая цифра года.pdf](https://github.com/Metrolog/marks/files/1426066/default.pdf)
Сместилась первая цифра года и немного цифра месяца. На файле новое клеймо наложено на строе.

**Comment by sergey-s-betke** [comment]
Решение указанной проблемы - в рамках #34.
