### ISSUE TITLE
Визульно неправильное размещение цифр года для цифр разной ширины

### ISSUE THREAD

**Issue by sergey-s-betke** [Metrolog/marks#34]
Повторно поднята проблема #25. В #32 вложен файл с примером ([смещена первая цифра года.pdf](https://github.com/Metrolog/marks/files/1426066/default.pdf)).

**Comment by sergey-s-betke** [comment]
В первую очередь необходимо решить, каким образом позиционировать цифры года и знак поверителя, чтобы они выглядели нормально. Видимо, придётся смещать знак поверителя, и центровать его между цифрами года, а не по отношению к контуру клейма.

**Comment by sergey-s-betke** [comment]
[test2.pdf](https://github.com/Metrolog/marks/files/1428149/test2.pdf)
[test.pdf](https://github.com/Metrolog/marks/files/1428150/test.pdf)
Так визуально выглядит лучше на мой взгляд...

**Comment by utalua** [comment]
Мне больше импонирует вариант, который был до смещения "АД".
Если рассматривать данный вариант, то я бы позиционировал шифр поверителя относительно середины шифра организации (или середины  круга), а цифры года привязать к контуру клейма (Единица будет чуть дальше от контура, что бы визуально от шифра поверителя цифры года были одинакова отдалены)
Хотя, всё это не принципиально.

**Comment by sergey-s-betke** [comment]
Алексей предлагает следующий вариант:
- [ ] знак поверителя размещаем по центру оттиска
- [ ] цифры года размещаем по центру относительно границ оттиска и знака поверителя

**Comment by sergey-s-betke** [comment]
Остановились на варианте, когда знак поверителя центруем относительно контура оттиска и цифры года центруем относительно половины оттиска. Аналогично - для калибровочных клейм.
