### ISSUE TITLE
Сделать вывод ударных клейм и плашек в файлах по одной штуке. Иерархия папок

### ISSUE THREAD

**Issue by utalua** [Metrolog/marks#69]
## Требуемое поведение

Было бы очень удобно, если после запуска сборки создавалась отдельная папка (название папки берется дата/время сборки) в папке release. Внутри этой новой папки, отдельно папки для стальных клейм и плашек (наименование из размера клейма). В этих папках каждое клеймо и плашка отдельным файлом PLT (наименование файла - номер шифра калибровщика).

Пример: 
10 стальных 6мм клейм с шифром поверителя от 5 до 15
5 плашек с шифром поверителя от 3, 6, 8, 10, 105
100 каучуковых клейм.
- После сборки в папке release появляется папка 11.07.2018 (11:18:22)
- В папке 11.07.2018 (11:18:22) появляется папка 6 mm, в которой 10 отдельных файлом PLT с наименованием 1, 2, 3, 4, 5, 6, 7, 8, 9, 10.
- В папке 11.07.2018 (11:18:22) появляется папка 8 mm, в которой 10 отдельных файлом PLT с наименованием 3, 6, 8, 10, 105.
- В папке 11.07.2018 (11:18:22) появляется появляется папка 18 mm, в которой файл PLT с наименованием 1-100.

1) Наименование папок могу сам прописывать, там же где прописываются клейма.
2) Если сразу не возможно так сделать, то могу для разных видов клейм делать разные сборки. Главное что бы в папке release создавалась еще одна папка.

## Текущее поведение

В данный момент после сборки всё собирается в один файл в папке release.
А дальше либо в ручную разбиваю клейма по размерам в короле, либо для каждого вида клейм делаю новые сборки.

**Comment by sergey-s-betke** [comment]
Для генерации нескольких файлов одним скриптом следует посмотреть параметры:

    gs -dSAFER -dBATCH -dNOPAUSE -r150 -sDEVICE=pnggray -dTextAlphaBits=4 -sOutputFile=doc-%02d.png doc.pdf

**Comment by sergey-s-betke** [comment]
И смотреть следует в сторону `eps2write`. Формат векторный, но поддерживаемый многими продуктами.

**Comment by sergey-s-betke** [comment]
Генерация множества файлов непосредственно из одного postscript файла не будет гибкой и переносимой. Именами файлов управлять можем крайне ограниченно, да и решение будет завязано исключительно на ghostscript. Кроме того, есть проблемы с вычислением зависимостей в make файлах.

Посему предложение такое:
- готовим postscript сценарий, принимающий параметры через командую строку ghostscript.
- этот сценарий будет за один вызов генерировать один выходной файл.
- через макросы в make файлах генерируем множества целей. Зависимости - собственно makefile и исходный postscript сценарий. Макросы обеспечат пакетную генерацию клейм.

В итоге у нас появится ещё один тип файлов для обработки заказов: makefile. Один файл на заказ. Но один файл будет порождать множество файлов результатов.

**Comment by sergey-s-betke** [comment]
`eps2write` применим. Хотя и префикс убийственный просто (`ProcSet /PDF`). Стоит поискать возможность отключения вывода этого префикса...

**Comment by sergey-s-betke** [comment]
Можно управлять выводом в разные файлы и из postscript:

  Note, some devices (e.g. pdfwrite, ps2write, ...) only write the output file upon exit, but changing the OutputFile device parameter will cause these devices to emit the pages received up to that point and then open the new file name given by OutputFile. 
  For example, in order to create two PDF files from a single invocation of ghostscript the following can be used:

    gs -sDEVICE=pdfwrite -o tiger.pdf examples/tiger.eps -c "<< /OutputFile (colorcir.pdf) >> setpagedevice" -f examples/colorcir.ps

**Comment by sergey-s-betke** [comment]
Однако. Требуется реализация полноценного цикла `for` в makefile. Такой возможности нет в GMSL.

Но можно задействовать `guile` - реализацию языка [Scheme](https://ru.wikipedia.org/wiki/Scheme) в GNU Make.

Возможно, ради скорости стоит отказаться от PowerShell в сторону guile...

**Comment by sergey-s-betke** [comment]
http://www.gnu.org/software/guile/manual/guile.pdf

**Comment by sergey-s-betke** [comment]
https://bitbucket.org/bjoli/guile-for-loops/src/45ecce6c2b2cc9f5124aea199207dd57393840fe/tests/tests.scm?at=default&fileviewer=file-view-default

**Comment by sergey-s-betke** [comment]
https://koketteriet.se/software/guile-for-loops/docs.html#org47969b4

**Comment by sergey-s-betke** [comment]
https://web-artanis.com/scheme.html

**Comment by sergey-s-betke** [comment]
Guile не поддерживается версией make на Circle CI. Видимо, придётся отключить сборку на Circle CI. Да и на Ubuntu на Appveyor пока так же.

**Comment by sergey-s-betke** [comment]
Возникла проблема с кодировкой передаваемых строковых параметров из Makefile в PostScript (#75). И пока внятного и удобного решения не вижу...

**Comment by sergey-s-betke** [comment]
Необходимо параметрами установить авторазмеры выводимых изображений по размерам клейм.

**Comment by sergey-s-betke** [comment]
Рассмотреть стоит `ps2epsi.ps` вместо `epswrite` для генерации файлов с меньшей преамбулой. Стоит попробовать.

**Comment by sergey-s-betke** [comment]
https://stackoverflow.com/questions/41139386/ghostscript-how-to-auto-crop-stdin-to-bounding-box-and-write-to-pdf/41180086

**Comment by sergey-s-betke** [comment]
Стоит посмотреть и в сторону `svgwrite`.

**Comment by sergey-s-betke** [comment]
Завершу решение этой задачи на примере #86. На .pcx, скажем.

**Comment by sergey-s-betke** [comment]
Генерация идёт успешно на примере .pcx и .tif. Эту задачу закрываю. Планирую включить в версии 2.3.

**Comment by sergey-s-betke** [comment]
Необходимо:

- [ ] добавить поддержку калибровочных клейм, ромбовидных клейм
- [ ] добавить в тесты многофайловую генерацию
- [ ] для тестов с многофайловым выводом в качестве артефакта формировать .zip архив

**Comment by sergey-s-betke** [comment]
Не забыть описать изменения в документации.

**Comment by sergey-s-betke** [comment]
Лишние зависимости:

    obj/mf/test_SP_2018_c/build_multifile_order.mk:  tests/mf/test_SP_2018_c.mk tests/mf/test_SP_2018_r.mk tests/mf/test_SP_2018_v.mk  tests/mf/test_SP_2018_c.mk  | $(TARGETDIR)

**Comment by sergey-s-betke** [comment]
- [ ] устранить ошибку #92
