### ISSUE TITLE
Добавить возможность сборки без указания индивидуального знака поверителя (ИЗП)

### ISSUE THREAD

**Issue by utalua** [Metrolog/marks#83]
## Требуемое поведение

Версией ранее сборка осуществлялась, когда я ничего не ставил в месте номера ИЗП, теперь при таком варианте сборка не осуществляется.

В некоторых случаях требуется выводить макет клейм без знака ИЗП

## Возможное решение

Добавить в список ИЗП номер 257 (или 0), которая будет пустым местом.

**Comment by sergey-s-betke** [comment]
Требуется указывать 0 (нуль) явно.

**Comment by utalua** [comment]
Попробовал, да, с нулем сборка осуществляется и место ИЗП остается пустым. Спасибо.

**Comment by sergey-s-betke** [comment]
Следует добавить об этом информацию в документации.
